<?php
/**
 * @file
 * Main code for Socrata module
 */

use Drupal\Core\Url;
use Drupal\socrata\Entity\Endpoint;

/**
 *  Implements hook_menu_links_discovered_alter().
 */
function socrata_menu_links_discovered_alter(&$links) {
  $links['entity.endpoint.add_form'] = [
    'title' => new \Drupal\Core\StringTranslation\TranslatableMarkup('Add endpoint'),
    'route_name' => 'entity.endpoint.add_form',
    'parent' => 'entity.endpoint.collection',
    'weight' => -50,
  ];
  // Adding links to /admin/structure/socrata.
  foreach (socrata_get_endpoints() as $machine_name => $label) {
    $links['entity.endpoint.edit_form.' . $machine_name] = array(
      'title' => new \Drupal\Core\StringTranslation\TranslatableMarkup($label),
      'route_name' => 'entity.endpoint.edit_form',
      'parent' => 'entity.endpoint.collection',
      'route_parameters' => array(
        'endpoint' => $machine_name,
      ),
    );
    if (\Drupal::moduleHandler()->moduleExists('devel')) {
      $links['entity.endpoint.devel_load.' . $machine_name] = array(
        'title' => t('Devel'),
        'route_name' => 'entity.endpoint.devel_load',
        'parent' => 'entity.endpoint.edit_form.' . $machine_name,
        'route_parameters' => array(
          'endpoint' => $machine_name,
        ),
      );
    }
    $links['entity.endpoint.delete_form.' . $machine_name] = array(
      'title' => new \Drupal\Core\StringTranslation\TranslatableMarkup('Delete'),
      'route_name' => 'entity.endpoint.delete_form',
      'parent' => 'entity.endpoint.edit_form.' . $machine_name,
      'route_parameters' => array(
        'endpoint' => $machine_name,
      ),
    );
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert( for menu entities.
 */
function socrata_endpoint_insert(Endpoint $endpoint) {
  if (\Drupal::moduleHandler()->moduleExists('admin_toolbar_tools')) {
    // Flushing all the caches is expensive, but is required to make the new
    // endpoint show up in the Structure menu.
    drupal_flush_all_caches();
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete() for menu entities.
 */
function socrata_endpoint_delete(Endpoint $endpoint) {
  if (\Drupal::moduleHandler()->moduleExists('admin_toolbar_tools')) {
    \Drupal::service('router.builder')->rebuild();
  }
}

/**
 * Return an associative array of endpoints.
 *
 * @return array
 *   An array with the machine-readable names as the keys, and human-readable
 *   titles as the values.
 */
function socrata_get_endpoints() {
  if ($endpoints = Endpoint::loadMultiple()) {
    foreach ($endpoints as $menu_name => $menu) {
      $endpoints[$menu_name] = $menu->label();
    }
    asort($endpoints);
  }
  return $endpoints;
}

/**
 * Create watchdog entry during debugging and try to call dpm from devel module.
 *
 * When debugging is disabled, nothing happens.
 *
 * Set the config variable socrata_debug = TRUE to generate log output
 *
 * @param array or object $msg
 * @param array $vars
 */
function _socrata_dbg($msg, $vars = array()) {
  if (!$vars) {
    $vars = array();
  }
  if (\Drupal::config('socrata.settings')->get('socrata_debug')) {
    \Drupal::logger('socrata')->debug((is_array($msg) || is_object($msg)) ? '<pre>' . print_r($msg, TRUE) . '</pre>' : $msg, []);
    if (\Drupal::moduleHandler()->moduleExists('devel')) {
      dpm((is_array($msg) || is_object($msg)) ? $msg : t($msg, $vars));
    }
  }
}

/**
 * Util function to resolve redirects.
 */
function _socrata_resolve_redirects($endpoint) {
  // Make sure we have a valid-looking endpoint.
  if (substr_compare($endpoint, '.json', -5)) {
    $endpoint .= '.json';
  }

  // Create a new cURL resource.
  $ch = curl_init();
  if ($ch) {
    // Pull and set custom curl options.
    // @FIXME
// Could not extract the default value because it is either indeterminate, or
// not scalar. You'll need to provide a default value in
// config/install/socrata.settings.yml and config/schema/socrata.schema.yml.
$curlopts = \Drupal::config('socrata.settings')->get('socrata_curl_options');

// Need to look at hook_socrata_curl_options_alter in D7 module.
//    \Drupal::moduleHandler()->alter('socrata_curl_options', $curlopts);
    curl_setopt_array($ch, $curlopts);

    // Set required curl options.
    $req_curlopts = array(
      CURLOPT_HEADER => TRUE,
      CURLOPT_RETURNTRANSFER => TRUE,
    );
    curl_setopt_array($ch, $req_curlopts);

    // Execute the request and cleanup.
    curl_setopt_array($ch, $curlopts);
    do {
      $url = Url::fromUri($endpoint, array('query' => array('$limit' => 1), 'absolute' => TRUE))->toString();

      curl_setopt($ch, CURLOPT_URL, $soda_url);
      $resp = curl_exec($ch);
      if (FALSE !== $resp) {
        // Pull info from response and see if we had an error.
        $info = curl_getinfo($ch);
        if ($info['http_code'] >= 400) {
          break;
        }
        else {
          // Split out response headers into name => value array.
          list($headers, $data) = explode("\r\n\r\n", $resp, 2);
          $headers = _socrata_parse_headers($headers);

          // Test for redirect in the event curl wasn't able
          // to automagically follow due to server config.
          if (!empty($headers['location'])) {
            $endpoint = $headers['location'];
          }
        }
      }
    } while (FALSE !== $resp && !empty($headers['location']));
  }

  return $endpoint;
}

/**
 * Util function to parse out HTTP response headers.
 */
function _socrata_parse_headers($headers) {
  $headers_arr = array();

  $headers = explode("\r\n", $headers);
  foreach ($headers as $header) {
    if ('HTTP' == substr($header, 0, 4)) {
      continue;
    }
    list($name, $value) = explode(':', $header, 2);
    $name = strtolower(trim($name));
    if (in_array($name, array('x-soda2-fields', 'x-soda2-types'))) {
      $headers_arr[$name] = json_decode($value);
    }
    else {
      $headers_arr[$name] = trim($value);
    }
  }

  return $headers_arr;
}
