socrata.settings:
  type: config_object
  label: Settings
  mapping:
    socrata_debug:
      type: boolean
    socrata_curl_options:
      type: sequence
socrata.endpoint.*:
  type: config_entity
  label: 'Endpoint config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
        type: label
        label: 'Name'
    url:
        type: string
        label: 'URL'
    app_token:
        type: string
        label: 'Application token'
